### ISSUE TITLE
checksum issues

### ISSUE THREAD

**Issue by mhenrixon** [madwork/chef-chruby-build#2]
I am unable to find all the checksums needed for all various versions and honestly that stuff isn't for me. Is there a way to turn that off somehow or can you point me to the various places to find the checksums or lastly could you update everything to the latest and greatest?

**Comment by mhenrixon** [comment]
Never mind I didn't like your approach at all with arc and stuff so using something else.

**Comment by madwork** [comment]
Hi @mhenrixon,

I think [opscode/ark](https://supermarket.chef.io/cookbooks/ark) is best way
> for managing software archives

The ruby checksum is not a required attribute, ark does not require this attribute:
https://github.com/burtlo/ark/tree/master/resources/default.rb#L50
https://github.com/burtlo/ark/tree/master/providers/default.rb#L44

You can definitely write a rubies data bag like that:
```json
{
  "id": "ruby-2.2.0",
  "url": "http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.0.tar.gz"
}
```

Checksums can be find for ruby versions in [downloads](https://www.ruby-lang.org/en/downloads/)

If it's not available in SHA256, I check MD5 and I compute SHA256 by myself:
```bash
shasum -a 256 -b ruby-2.2.0.tar.gz
```

About libyaml and google perftools, I computed SHA256 checksums with downloaded packages.
